name: ClockIn

on:
  push:
    branches: 
      - master
  watch:
    types: started
  schedule:
    - cron: 0 */12 * * *

jobs:
  ClockIn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install python3
        run: |
          sudo -E apt-get -yqq update
          sudo -E apt-get -yqq install python3
          pip install dingtalkchatbot
      - name: Clock In
        env:
          ACCOUNT: ${{ secrets.ACCOUNT }}
          PASSWORD: ${{ secrets.PASSWORD }}
          #WEBHOOK_KEY: ${{ secrets.WEBHOOK_KEY }}
          #AT_MOBILES: ${{ secrets.AT_MOBILES }}
        run: |
          python3 clock-in.py ${ACCOUNT} ${PASSWORD}
